### ISSUE TITLE
TransportContext.java:352|Fatal (HANDSHAKE_FAILURE): no cipher suites in common (  "throwable"

### ISSUE THREAD

**Issue by steep8** [intoolswetrust/ldap-server#66]
Tried to run ldaps on Ubuntu but it does not work, ldap - ok.

Environment:
oc: Ubuntu 22.04.1
OS name: "linux", version: "6.5.0-28-generic", arch: "amd64", family: "unix"
ldap-server version: v.1.0.0
openjdk 11.0.22
Apache Maven 3.6.3

Steps:
1. Create key store:
keytool -validity 365 -genkey -alias lda-example -keyalg RSA -keystore ../ldap-ad-it/keystore/ldap.example.keystore -storepass 1Q2w3e4r -keypass 1Q2w3e4r -dname cn=ldap.example
2. Run server:
java -Djavax.net.debug=all -jar target/ldap-server.jar -sp 10636 -skf ../ldap-ad-it/keystore/ldap.example.keystore -skp 1Q2w3e4r 
3. Run client
LDAPTLS_REQCERT=never  ldapsearch -H ldaps://ldap.example:10636 -x -b "ou=users,dc=ldap,dc=example" -D "uid=admin,ou=system" -w secret

Expected result:
some data from ldap request

Actual Result:
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)

Attached you can find ldap server log:

[HANDSHAKE_FAILURE.txt](https://github.com/user-attachments/files/15510935/HANDSHAKE_FAILURE.txt)

**Comment by glmcz** [comment]
Hi 

I was able to reproduce your issue. So far I think that the problem is not with the server. Because I used jExplorer and i was able to connect and search for information from the server. 
I guess that problem was with certificates. We should define CA as localhost and then it works. 

So the client should have only generated the certificate from the server's key pair stored in the JKS keystore. That is it. It is so simple, that it is hard to get it :D


btw. Djavax.net.debug=all gives me only bad clues...

**Comment by steep8** [comment]
> So far I think that the problem is not with the server. 
Right
>I guess that problem was with certificates. We should define CA as localhost and then it works.
Thanks. I regenerated certificates and ldaps works ok after it.
The problem was in certificates.

**Comment by poddubetskyi** [comment]
У мене Windows 11 та Java 17. Жоден з варіантів генерації зовнішнього ключа і його подальшого використання не спрацював для мене: підключення до `ldap-server` завершується помилкою, як і у автора розмови.
Проте якщо запустити сервер взагалі без зовнішнього ключа,
```cmd
java.exe ^
 -Dlog4j.logger.org.apache.directory.server=DEBUG ^
 -Djavax.net.debug=all ^
 -jar .\ldap-server-v1.0.0.jar ^
 -sep TLSv1.2 ^
 -sp 636
```
то автоматично генерується ключ за замовчуванням і з ним SSL-з'єднання встановлюється успішно.

Параметри ключа за замовчуванням виявляються такими:
```
X509 Certificate:
Version: 1
Serial Number: 019dd532c249
Signature Algorithm:
    Algorithm ObjectId: 1.2.840.113549.1.1.5 sha1RSA
    Algorithm Parameters:
    05 00
Issuer:
    CN=ApacheDS
    OU=Directory
    O=ASF
    C=US
  Name Hash(sha1): d2f4cf913dee7689dfd1cf94d71c962b89e5a01e
  Name Hash(md5): d05e575a79344907b95fd448afb6114b

 NotBefore: 28.04.2026 20:46
 NotAfter: 28.04.2027 20:46

Subject:
    CN=%COMPUTERNAME%
    OU=Directory
    O=ASF
    C=US

```

Де `%COMPUTERNAME%` містить те саме значення, що і відповідна змінна Windows.

Спроби генерувати окремий самопідписний ключ, самопідписний ключ CA з подальшим його використанням для підписання ключа сервера завершилися безрезультатно: ознаки того, що ключ використовується в роботі `ldap-server`  були відсутні.

Зокрема було сформовано ключі з використанням таких команд:
```cmd
rem 1) Generate the CA Certificate (Self-Signed)

keytool.exe -genkeypair ^
  -alias root-ca-at-localhost ^
  -keyalg RSA ^
  -keysize 4096 ^
  -sigalg SHA384withRSA ^
  -dname "CN=localhost" ^
  -ext bc=ca:true ^
  -validity 3650 ^
  -keystore root-ca.keystore ^
  -storepass somePassword ^
  -keypass somePassword

rem 2) Generate Server Keypair for ApacheDS

keytool.exe -genkeypair ^
  -alias apacheds-ldap-example-server ^
  -keyalg RSA ^
  -keysize 4096 ^
  -sigalg SHA384withRSA ^
  -dname "CN=localhost" ^
  -ext san=dns:localhost,ip:127.0.0.1 ^
  -validity 365 ^
  -keystore server-key.keystore ^
  -storepass somePassword ^
  -keypass somePassword

rem 3) Sign the Server Certificate with the Local CA
rem 3.1) Export the CA certificate:
keytool.exe -exportcert ^
  -alias root-ca-at-localhost ^
  -file root-ca-at-localhost.crt ^
  -keystore root-ca.keystore ^
  -storepass somePassword

rem 3.2) Generate CSR for ApacheDS:
keytool.exe -certreq ^
  -alias apacheds-ldap-example-server ^
  -file apacheds-ldap-example-server.csr ^
  -keystore server-key.keystore ^
  -storepass somePassword

rem 3.3) Sign CSR with CA:
keytool.exe -gencert ^
  -alias root-ca-at-localhost ^
  -infile apacheds-ldap-example-server.csr ^
  -outfile apacheds-ldap-example-server.crt ^
  -validity 365 ^
  -keystore root-ca.keystore ^
  -storepass somePassword

rem 4) Import CA and Signed Cert into ApacheDS Keystore:
rem у разі використання двох окремих сховищ
rem сертифікат центру сертифікації має бути імпортований
rem до сховища з ключем сервера
keytool.exe -importcert ^
  -alias root-ca-at-localhost ^
  -file root-ca-at-localhost.crt ^
  -noprompt ^
  -keystore server-key.keystore ^
  -storepass somePassword 


keytool.exe -importcert ^
  -alias apacheds-ldap-example-server ^
  -file apacheds-ldap-example-server.crt ^
  -keystore server-key.keystore ^
  -storepass somePassword 
```

Команда запуску `ldap-server`:
```cmd
java.exe ^
 -Dlog4j.logger.org.apache.directory.server=DEBUG ^
 -Djavax.net.debug=all ^
 -jar .\ldap-server.jar ^
 -sep TLSv1.2 ^
 -sp 636 ^
 -skf server-key.keystore ^
 -skp somePassword
```
Попри всі докладені зусилля спроба підключення до `ldap-server`,  запущеного зі згенерованим у зазначений спосіб ключем сервера завершується помилкою, як і у автора розмови. 🙁

**Comment by kwart** [comment]
Hi, thanks for the detailed report — that's enough to spot it.

The problem is the keystore **format**. Since Java 9, `keytool -genkeypair` defaults to **PKCS12** when no `-storetype` is specified, but `ldap-server` (via ApacheDS) loads the keystore as **JKS** (see the README note about "JKS keystore"). So your `server-key.keystore` is silently the wrong type — ApacheDS can't read the key from it, which is why it looks like the key isn't being used.

Two ways to fix it:

1. Add `-storetype JKS` to every `keytool` command, e.g.:
   ```cmd
   keytool.exe -genkeypair -storetype JKS -alias apacheds-ldap-example-server ...
   ```
2. Or convert the existing PKCS12 keystore to JKS:
   ```cmd
   keytool.exe -importkeystore ^
     -srckeystore server-key.keystore -srcstoretype PKCS12 -srcstorepass somePassword ^
     -destkeystore server-key.jks      -deststoretype JKS   -deststorepass somePassword
   ```
   and then start the server with `-skf server-key.jks`.

Your import order (CA first, then re-importing the signed cert under the same alias as the private key) is correct — only the storetype is wrong.

**Comment by poddubetskyi** [comment]
Вітаю!
Порада щодо перетворення формату сховища ключів з PKCS12 на JKS виявилася дієвою.
Після перетворення спроба запуску сервера з ключем, що розташований у сховищі JKS завершилася успішно.
Спроба підключення до запущеного таким чином сервера з використанням команди `openssl s_client` також завершилася відображенням звіту про факт використання шифрування у встановленому з'єднанні:
Команда:
```
echo Q | openssl s_client -connect localhost:636 -brief
```
Результат:
```
Can't use SSL_get_servername
depth=1 CN = localhost
verify error:num=19:self signed certificate in certificate chain
CONNECTION ESTABLISHED
Protocol version: TLSv1.2
Ciphersuite: ECDHE-RSA-AES256-GCM-SHA384
Peer certificate: CN = localhost
Hash used: SHA256
Signature type: RSA-PSS
Verification error: self signed certificate in certificate chain
Server Temp Key: X25519, 253 bits
DONE
```
Дякую!
👍
